  - alias: common.systemStarted
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: script.pb_notify
        data_template:
          title: Common
          text: Server Started on {{ states('sensor.git') }}
          
### MQTT ###
  - alias: MQTT.PUB.ClimaTempChange
    trigger:
      platform: state
      entity_id: sensor.climate_room_temp
    action:
      - service: script.pb_debug
        data_template:
          title: climate_room_temp
          text: Temperature Changed  to {{ states('sensor.climate_room_temp') }}
      - service: mqtt.publish
        data:
          topic: home/clima/current
          payload_template: "{{ states('sensor.climate_room_temp') }}"
          retain: 'true'
      - service: script.save_home_temp 
### NOTFY UPDATE ###      
  - alias: notify.updateAvailable
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      - service: persistent_notification.create
        data_template:
          title: "NEW HASS : version {{ states.updater.updater.state}}"
          message: "{{ states.updater.updater.attributes.release_notes}}"
      - service: notify.pb
        data_template:
            {
          "title": "NEW HASS : version {{ states.updater.updater.state}}",
          "message": "{{ states.updater.updater.attributes.friendly_name}}",
          "data":{"url": "{{ states.updater.updater.attributes.release_notes}}"}
          }  
