# - alias: 'alarm.setAlarmBySensors'
  # trigger:
    # - platform: state
      # entity_id: binary_sensor.motion_sensor
      # to: 'on'
    # - platform: state
      # entity_id: binary_sensor.front_door
      # to: 'on'
  # condition:
    # - condition: state
      # entity_id: alarm_control_panel.ha_alarm
      # to: armed_away
  # action:
    # service: alarm_control_panel.alarm_trigger
    # entity_id: alarm_control_panel.ha_alarm
automation:
- alias: 'Trigger alarm while armed away'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.ha_alarm