# automation:
script:
  mqtt_temp_set:
    alias: Save Temperatures
    sequence:
    - service: mqtt.publish
      data:
        topic: home/clima/home
        payload_template: '{{ states(''input_slider.clima_home_temp'') }}'
        retain: 'true'
    - service: mqtt.publish
      data:
        topic: home/clima/away
        payload_template: '{{ states(''input_slider.clima_away_temp'') }}'
        retain: 'true'
        
  save_home_temp:
    alias: Save Home Temperature
    sequence:
    - condition: state
      entity_id: input_select.mode
      state: 'Home'
    - service: mqtt.publish
      data:
        topic: home/clima/home
        payload_template: '{{ states.sensor.climate_room_temp.state }}'
        retain: 'true'
    - service: script.pb_debug
      data_template:
        title: CLIMA
        text: Home Temperature {{ states.input_slider.clima_home_temp.state }} Saved 
        
  warmup:
    alias: Warmup
    sequence:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.room
        temperature: "{{ states.sensor.home_temp.state | float }}"
    - service: script.pb_debug
      data_template:
        title: CLIMA
        text: Home Temperature {{ states.sensor.home_temp.state }} Saved 

climate:
  - platform: generic_thermostat
    name: Room
    heater: switch.heating
    target_sensor: sensor.heater_temp
    min_temp: 19
    max_temp: 30
    target_temp: 20
    tolerance: 2
    
sensor:
  - platform: mqtt
    name: "Heater Temp"
    state_topic: "tele/sonoff2/SENSOR"
    unit_of_measurement: '°C'
    value_template: "{{value_json.DS18B20.Temperature}}"
    
  - platform: mqtt
    name: "Home Temp"
    state_topic: "home/clima/home"
    unit_of_measurement: '°C'
    
  - platform: mqtt
    name: "Away Temp"
    state_topic: "home/clima/away"
    unit_of_measurement: '°C'
    
  - platform: mqtt
    name: "Current Temp"
    state_topic: "home/clima/current"
    unit_of_measurement: '°C'
    
  - platform: template
    sensors:
      climate_room_temp:
        value_template: '{{states.climate.room.attributes.temperature}}'
        friendly_name: 'Climate temp'
        unit_of_measurement: '°C'

input_slider:
  clima_home_temp:
    name: Home Temp
    min: 10
    max: 30
    step: 0.5
    initial: 20
    icon: mdi:temperature-celsius
  clima_away_temp:
    name: Away Temp
    min: 10
    max: 30
    step: 0.5
    initial: 10
    icon: mdi:temperature-celsius
    
group:
  clima:
    name: Clima Indoor
    entities:
    - climate.room
    - group.heater

  heater:
    name: Clima Dev
    control: hidden
    icon: mdi:tune
    entities:
    - switch.heating
    - sensor.heater
    - sensor.current_temp
    - sensor.home_temp
    - sensor.away_temp
    - input_slider.clima_home_temp
    - input_slider.clima_away_temp
    - script.mqtt_temp_set
    - script.warmup