shell_command:
  get_latest_config: sudo bash /config/bin/pullconfig.sh
  get_master: sudo bash /config/bin/git_master.sh
  get_sandbox: sudo bash /config/bin/git_sandbox.sh

script:
  update_config:
    sequence:
      - service: shell_command.get_latest_config
      - service: homeassistant.restart
  git_master:
    sequence:
      - service: shell_command.get_master
      - service: homeassistant.restart
  git_sandbox:
    sequence:
      - service: shell_command.get_sandbox
      - service: homeassistant.restart

group:
  git:
    entities:
      - group.gitin
  gitin:
    name: git
    entities:
      - script.update_config
      - script.git_master
      - script.git_sandbox
#      - sensor.commits

sensor:
  - platform: command_line
    name: sensor
    command: "sudo bash /config/bin/git_branch.sh"
    unit_of_measurement: "Branch"
  - platform: command_line
    name: commits
    command: "sudo bash /config/bin/git_commits.sh"
    unit_of_measurement: "Commit"

homeassistant:
  customize:
    group.gitin:
      custom_ui_state_card: state-card-custom-ui
      extra_badge:
        entity_id: sensor.commits
      hide_control: true
      icon: mdi:git
      blacklist_states: 0
      extra_data_template: ${ entities['sensor.git'].state}