automation:
  - alias: motion_kitchen_on
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001a40748
      to: 'on'
    action:
    - service: script.motion_light_timer_kitchen_start
    - service: script.motion_watchdog_init
      data:
        place: Kitchen

  - alias: motion_kitchen_end
    initial_state: 'off'
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001a40748
      to: 'off'
    condition:
      condition: state
      entity_id: input_boolean.motion_light_kitchen
      state: 'on'
    action:
    - service: script.motion_light_timer_kitchen_end

script:
  motion_light_timer_kitchen_end:
    alias: MOTION.light.timer.kitchen.end
    sequence:
    - delay: 00:{{ states.input_number.motion_light_kitchen_delay.state | int }}:00
    - service: light.turn_off
      entity_id: light.600194955cb6_19216831113
    - service: automation.turn_off
      entity_id: automation.motion_kitchen_end

  motion_light_timer_kitchen_start:
    alias: MOTION.light.timer.kitchen.start
    sequence:
    - condition: state
      entity_id: input_boolean.motion_light_kitchen
      state: 'on'
    - service: script.turn_off
      entity_id: script.motion_light_timer_kitchen_end
    - service: light.turn_on
      entity_id: light.600194955cb6_19216831113
    - service: automation.turn_on
      entity_id: automation.motion_kitchen_end

input_boolean:    
  motion_light_kitchen:
    name: Motion light Kitchen
    initial: off
    icon: mdi:run
    
input_number:
  motion_light_kitchen_delay:
   name: Kitchen light Delay
   min: 1
   max: 60
   step: 1
   initial: 5
   icon: mdi:timer
   mode: box

group:
  motion_kitchen:
    name: Motion Kitchen
    entities:
    - binary_sensor.motion_sensor_158d0001a40748
    - input_boolean.motion_light_kitchen
    - input_number.motion_light_kitchen_delay
    - automation.motion_kitchen_end
    - automation.motion_kitchen_on
    - script.motion_light_timer_kitchen_start
    - script.motion_watchdog_init
    - script.motion_light_timer_kitchen_end


homeassistant:
  customize:
    group.motion_kitchen:
      # custom_ui_state_card: custom-ui
      # extra_badge:
      #   entity_id: binary_sensor.motion_sensor_158d0001a40748
      hide_control: true
      icon: mdi:run
    binary_sensor.motion_sensor_158d0001a40748:
      # custom_ui_state_card: custom-ui
      device_class: motion
      friendly_name: Kitchen Motion
    sensor.illumination_158d0001a40748:
      friendly_name: Kitchen Light
      icon: mdi:weather-sunny
      show_last_changed: true