automation:
  - alias: motion.DetectedWc
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001656a38
      to: 'on'
    action:
      - service: timer.start
        entity_id: timer.wc
#      - service: script.motion_light_timer_wc_start
      - service: script.motion_watchdog_init
        data:
          place: Wc
  
  - alias: motion.EndWc
    initial_state: 'off'
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001656a38
      to: 'off'
    condition:
      condition: state
      entity_id: input_boolean.motion_light_wc
      state: 'on'
    action:
      - service: script.motion_light_timer_wc_end

  - alias: timer finished
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.wc
    action:
      - service: script.pb_debug
        data_template:
          title: Timer
          text: Finished

  - alias: timer cancelled
    trigger:
      platform: event
      event_type: timer.cancelled
      event_data:
        entity_id: timer.wc
    action:
      - service: script.pb_debug
        data_template:
          title: Timer
          text: cancelled

  - alias: timer started
    trigger:
      platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.wc
    action:
      - service: script.pb_debug
        data_template:
          title: Timer
          text: started


script:
  motion_light_timer_wc_end:
    alias: MOTION.light.timer.wc.end
    sequence:
    - delay: 00:{{ states.input_number.motion_light_wc_delay.state | int }}:00
    - service: switch.turn_off
      entity_id: switch.wc_switch
    - service: automation.turn_off
      entity_id: automation.motionendwc

  motion_light_timer_wc_start:
    alias: MOTION.light.timer.wc.start
    sequence:
    - condition: state
      entity_id: input_boolean.motion_light_wc
      state: 'on'
    - service: script.turn_off
      entity_id: script.motion_light_timer_wc_end
    - service: switch.turn_on
      entity_id: switch.wc_switch
    - service: automation.turn_on
      entity_id: automation.motionendwc

timer:
  wc:
    duration: '00:00:30'
input_boolean:
  motion_light_wc:
    name: Motion light Wc
    initial: off
    icon: mdi:run

input_number:
  motion_light_wc_delay:
   name: Wc light Delay
   min: 1
   max: 60
   step: 1
   initial: 5
   icon: mdi:timer

group:
  motion_wc:
    name: Motion Wc
    entities:
    - binary_sensor.motion_sensor_158d0001656a38
    - input_boolean.motion_light_wc
    - input_number.motion_light_wc_delay

homeassistant:
  customize:
    group.motion_wc:
      custom_ui_state_card: state-card-custom-ui
      extra_badge:
        entity_id: binary_sensor.motion_sensor_158d0001656a38
      hide_control: true
      icon: mdi:run
    sensor.illumination_158d0001656a38:
      friendly_name: Wc Light
      icon: mdi:weather-sunny
    binary_sensor.motion_sensor_158d0001656a38:
      custom_ui_state_card: state-card-custom-ui
      device_class: motion
      friendly_name: Wc Motion
      show_last_changed: true