automation:
  - alias: motion.DetectedRoom
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d00016db268
      to: 'on'
    action:
      - service: script.motion_light_timer_room_start
      - service: script.motion_watchdog_init
        data:
          place: Room
  
  - alias: motion.EndRoom
    initial_state: 'off'
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d00016db268
      to: 'off'
    condition:
      condition: state
      entity_id: input_boolean.motion_light_room
      state: 'on'
    action:
      - service: script.motion_light_timer_room_end

script:
  motion_light_timer_room_end:
    alias: MOTION.light.timer.room.end
    sequence:
    - delay: 00:{{ states.input_number.motion_light_room_delay.state | int }}:00
    - service: switch.turn_off
      entity_id: switch.living_switch_1

  motion_light_timer_room_start:
    alias: MOTION.light.timer.room.start
    sequence:
    - condition: state
      entity_id: input_boolean.motion_light_room
      state: 'on'
    - service: script.turn_off
      entity_id: script.motion_light_timer_room_end
    - service: switch.turn_on
      entity_id: switch.living_switch_1
    - service: automation.turn_on
      entity_id: automation.motionendroom

input_boolean:
  motion_light_room:
    name: Motion light Room  
    initial: off
    icon: mdi:run

input_number:
  motion_light_room_delay:
   name: Room light Delay
   min: 1
   max: 60
   step: 1
   initial: 5
   icon: mdi:timer
   mode: box

group:
  motion_room:
    name: Motion Room
    entities:
    - binary_sensor.motion_sensor_158d00016db268
    - input_boolean.motion_light_room
    - input_number.motion_light_room_delay

homeassistant:
  customize:
    group.motion_room:
      custom_ui_state_card: custom-ui
      extra_badge:
        entity_id: binary_sensor.motion_sensor_158d00016db268
      hide_control: true
      icon: mdi:run
    sensor.illumination_158d00016db268:
      friendly_name: Room Light
      icon: mdi:weather-sunny
    binary_sensor.motion_sensor_158d00016db268:
      custom_ui_state_card: custom-ui
      device_class: motion
      friendly_name: Room Motion
      show_last_changed: true