automation:
  - alias: motion.DetectedHall
    trigger:
      platform: state
      entity_id: binary_sensor.motion_hall
      to: 'on'
    action:
     - service: script.motion_light_timer_hall_start
     - service: script.motion_watchdog_init
       data:
         place: Hall
  
  - alias: motion.EndHall
    initial_state: 'off'
    trigger:
      platform: state
      entity_id: binary_sensor.motion_hall
      to: 'off'
    condition:
     condition: state
     entity_id: input_boolean.motion_light_hall
     state: 'on'
    action:
     - service: script.motion_light_timer_hall_end

script:
  motion_light_timer_hall_end:
    alias: MOTION.light.timer.hall.end
    sequence:
    - delay: 00:00:{{ states.input_number.motion_light_hall_delay.state | int }}
    - service: switch.turn_off
      entity_id: switch.hall
      
  motion_light_timer_hall_start:
    alias: MOTION.light.timer.hall.start
    sequence:
    - condition: state
      entity_id: input_boolean.motion_light_hall
      state: 'on'
    - service: script.turn_off
      entity_id: script.motion_light_timer_hall_end
    - service: switch.turn_on
      entity_id: switch.hall
    - service: automation.turn_on
      entity_id: automation.motionendhall

input_boolean:
  motion_light_hall:
    name: Motion light Hall
    initial: on
    icon: mdi:run

input_number:
  motion_light_hall_delay:
   name: Hall light Delay
   min: 1
   max: 60
   step: 10
   initial: 30
   icon: mdi:timer
   mode: box

group:
  motion_hall:
    name: Motion Hall
    entities:
    - binary_sensor.motion_sensor_hall
    - binary_sensor.motion_hall
    - input_boolean.motion_light_hall
    - input_number.motion_light_hall_delay

homeassistant:
  customize:
    group.motion_hall:
      # custom_ui_state_card: custom-ui
      # extra_badge:
      #   entity_id: binary_sensor.motion_hall
      hide_control: true
      icon: mdi:run
    binary_sensor.motion_hall:
      # custom_ui_state_card: custom-ui
      show_last_changed: true
      device_class: motion
      friendly_name: Hall Motion

binary_sensor:
  - platform: rpi_gpio
    invert_logic: false
    pull_mode: DOWN
    ports:
     12: Motion Hall
