automation:
  - alias: Inputs visibility
    trigger:
      platform: state
      entity_id: media_player.yamaha_receiver
    action:
      service: script.group_visibility
      data:
        entity_id: group.yamaha_input
        cond: media_player.yamaha_receiver
        visible_state: 'on'
script:
  tv_shutdown_timer:
    alias: TV.shutdown_timer.
    sequence:
    - delay: 00:{{ states.input_number.tv_timer.state | int }}:00
    - service: switch.turn_off
      entity_id: switch.tv
  tv_on:
    alias: TV on
    sequence:
    - service: media_player.turn_on
      entity_id: media_player.yamaha_receiver
    - service: switch.turn_on
      entity_id: switch.tvrelay
    - service: media_player.select_source
      data:
        entity_id: media_player.yamaha_receiver
        source: miTV
  tv_off:
    alias: TV off
    sequence:
    - service: media_player.turn_off
      entity_id: media_player.yamaha_receiver
    - service: switch.turn_off
      entity_id: switch.tvrelay

  play_spotify_alexa:
    alias: play Spotify on Alexa
    sequence:
    - service: media_player.turn_on
      entity_id: media_player.yamaha_receiver
    - service: media_player.select_source
      data:
        entity_id: media_player.yamaha_receiver
        source: Alexa
    - service: media_player.select_source
      data:
        entity_id: media_player.spotify
        source: "eufy Genie-63F0"
    - service: media_player.media_play
      entity_id: media_player.spotify

  play_spotify_echo:
    alias: play Spotify on echo
    sequence:
    - service: media_player.turn_on
      entity_id: media_player.yamaha_receiver
    - service: media_player.select_source
      data:
        entity_id: media_player.yamaha_receiver
        source: Bluetooth
    - service: media_player.select_source
      data:
        entity_id: media_player.spotify
        source: "Dmitri's Echo Dot"
    - service: media_player.media_play
      entity_id: media_player.spotify

  play_spotify_chromecast:
    alias: play Spotify on chromecast
    sequence:
    - service: media_player.turn_on
      entity_id: media_player.yamaha_receiver
    - service: media_player.select_source
      data:
        entity_id: media_player.yamaha_receiver
        source: ChromeCast
    - service: media_player.select_source
      data:
        entity_id: media_player.spotify
        source: "Receiver"
    - service: media_player.media_play
      entity_id: media_player.spotify
  play_spotify_tv:
    alias: play Spotify on tv
    sequence:
    - service: media_player.turn_on
      entity_id: media_player.yamaha_receiver
    - service: media_player.select_source
      data:
        entity_id: media_player.yamaha_receiver
        source: miTV
    - service: media_player.select_source
      data:
        entity_id: media_player.spotify
        source: "TV"
    - service: media_player.media_play
      entity_id: media_player.spotify

  yamaha_source_blue:
    alias: Input Bluetooth
    sequence:
    - service: media_player.select_source
      data:
        entity_id: media_player.yamaha_receiver
        source: Bluetooth
  yamaha_source_tv:
    alias: Input tv
    sequence:
    - service: media_player.select_source
      data:
        entity_id: media_player.yamaha_receiver
        source: miTV
  yamaha_source_alexa:
    alias: Input Alexa
    sequence:
    - service: media_player.select_source
      data:
        entity_id: media_player.yamaha_receiver
        source: Alexa
  yamaha_source_hdmi2:
    alias: Input HDMI2
    sequence:
    - service: media_player.select_source
      data:
        entity_id: media_player.yamaha_receiver
        source: PC
  yamaha_source_av1:
    alias: Input AV1
    sequence:
    - service: media_player.select_source
      data:
        entity_id: media_player.yamaha_receiver
        source: ChromeCast


switch:
  - platform: mqtt
    state_topic: "stat/sonoff3/POWER"
    command_topic: "cmnd/sonoff3/POWER"
    #availability_topic: "tele/sonoff3/LWT"
    name: "TVrelay"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: template
    switches:
      tv:
        value_template: "{{ is_state('switch.tvrelay', 'on') }}"
        turn_on:
          service: script.tv_on
        turn_off:
          service: script.tv_off
      yamaha_reciever:
        friendly_name: "Receiver"
        value_template: "{{ is_state('media_player.yamaha_receiver', 'on') }}"
        turn_on:
          service: media_player.turn_on
          entity_id: media_player.yamaha_receiver
        turn_off:
          service: media_player.turn_off
          entity_id: media_player.yamaha_receiver

input_number:
  tv_timer:
    name: Tv Timer
    min: 1
    max: 90
    step: 1
    initial: 30
    icon: mdi:timer
    mode: box

sensor:
  - platform: template
    sensors:
      tv_timer:
        value_template: '{{ states("input_number.tv_timer") }}'
        friendly_name: 'Timer'
        unit_of_measurement: Min
      spotify_input:
        value_template: '{{ states.media_player.spotify.attributes.source}}'
        friendly_name: Spotfy
        icon_template: mdi:spotify
#        unit_of_measurement: Min
      yamaha_input:
        friendly_name: Reciever
        icon_template: mdi:speaker
        value_template:  >-
            {% if states.media_player.yamaha_receiver.state == "off" %}
            OFF
            {% else %}
            {{ states.media_player.yamaha_receiver.attributes.source}}
            {% endif %}
      tv:
        value_template: '{{ states.switch.tvrelay.state.upper()}}'
        friendly_name: 'TV'
        icon_template: mdi:monitor

group:
  media:
    name: Media
    view: true
    icon: mdi:play-circle-outline
    entities:
    - sensor.spotify_input
    - sensor.tv
    - sensor.yamaha_input
    - group.tv_switch
    - group.Tv
    - group.yamaha_input
  tv:
    name: Tv
    entities:
#    - switch.tv
#    - group.tv_switch
    - group.tv_timer
  tv_switch:
    name: Tv Switch
    entities:
    - switch.tvrelay
    - switch.yamaha_reciever

  tv_timer:
    name: Tv Timer
    entities:
#    - sensor.tv_timer
    - input_number.tv_timer
    - script.tv_shutdown_timer
  yamaha_input:
    name: Reciever
    entities:
    - script.yamaha_source_tv
    - script.yamaha_source_hdmi2
    - script.yamaha_source_blue
    - script.yamaha_source_alexa
    - script.yamaha_source_av1
    - script.play_spotify_echo
    - script.play_spotify_chromecast
    - script.play_spotify_alexa
    - media_player.yamaha_receiver
    - media_player.tv
    - media_player.spotify

homeassistant:
  customize:
    group.tv_timer:
      custom_ui_state_card: state-card-custom-ui
      extra_badge:
        entity_id: sensor.tv_timer
      icon: mdi:timer
    group.tv_switch:
      custom_ui_state_card: state-card-custom-ui
      extra_badge:
        entity_id: sensor.yamaha_input
      icon: mdi:monitor
    switch.tvrelay:
      icon: mdi:monitor
      friendly_name: TV
    switch.yamaha_reciever:
      icon: mdi:speaker
    group.yamaha_input:
      custom_ui_state_card: state-card-custom-ui
      extra_badge:
        entity_id: sensor.yamaha_input
      hide_control: true
      icon: mdi:git
      extra_data_template: ${ entities['sensor.spotify_input'].state}
