script:
  tv_shutdown_timer:
    alias: TV.shutdown_timer.
    sequence:
    - delay: 00:{{ states.input_slider.tv_timer.state | int }}:00
    - service: switch.turn_off
      entity_id: switch.tv
  tv_on:
    alias: TV on
    sequence:
    - service: media_player.turn_on
      entity_id: media_player.yamaha_receiver
    - service: switch.turn_on
      entity_id: switch.tvrelay
    - service: media_player.select_source
      data:
        entity_id: media_player.yamaha_receiver
        source: miTV
  tv_off:
    alias: TV off
    sequence:
    - service: media_player.turn_off
      entity_id: media_player.yamaha_receiver
    - service: switch.turn_off
      entity_id: switch.tvrelay

  play_spotify_alexa:
    alias: play Spotify on Alexa
    sequence:
    - service: media_player.turn_on
      entity_id: media_player.yamaha_receiver
    - service: media_player.select_source
      data:
        entity_id: media_player.yamaha_receiver
        source: Alexa
    - service: media_player.select_source
      data:
        entity_id: media_player.spotify
        source: "eufy Genie-63F0"
    - service: media_player.media_play
      entity_id: media_player.spotify

  play_spotify_echo:
    alias: play Spotify on echo
    sequence:
    - service: media_player.turn_on
      entity_id: media_player.yamaha_receiver
    - service: media_player.select_source
      data:
        entity_id: media_player.yamaha_receiver
        source: Bluetooth
    - service: media_player.select_source
      data:
        entity_id: media_player.spotify
        source: "Dmitri's Echo Dot"
    - service: media_player.media_play
      entity_id: media_player.spotify

  yamaha_source_blue:
    alias: Input Bluetooth
    sequence:
    - service: media_player.select_source
      data:
        entity_id: media_player.yamaha_receiver
        source: Bluetooth
  yamaha_source_tv:
    alias: Input tv
    sequence:
    - service: media_player.select_source
      data:
        entity_id: media_player.yamaha_receiver
        source: miTV
  yamaha_source_alexa:
    alias: Input Alexa
    sequence: 
    - service: media_player.select_source
      data:
        entity_id: media_player.yamaha_receiver
        source: Alexa

switch:
  - platform: mqtt
    state_topic: "stat/sonoff3/POWER"
    command_topic: "cmnd/sonoff3/POWER"
    #availability_topic: "tele/sonoff3/LWT"
    name: "TVrelay"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: template
    switches:
      tv:
        value_template: "{{ is_state('switch.tvrelay', 'on') }}"
        turn_on:
          service: script.tv_on
        turn_off:
          service: script.tv_off

input_slider:
  tv_timer:
    name: Tv Timer
    min: 5
    max: 90
    step: 5
    initial: 30
    icon: mdi:timer

sensor:
  - platform: template
    sensors:
      tv_timer:
        value_template: '{{ states("input_slider.tv_timer") }}'
        friendly_name: 'Timer'
        unit_of_measurement: Min
  - platform: template
    sensors:
      spotify_input:
        value_template: '{{ states.media_player.spotify.attributes.source}}'
        friendly_name: Spotfy
        icon_template: mdi:spotify
#        unit_of_measurement: Min
  - platform: template
    sensors:
      yamaha_input:
        value_template: '{{ states.media_player.yamaha_receiver.attributes.source}}'
        friendly_name: Reciever
        icon_template: mdi:speaker
#        unit_of_measurement: Min

group:
  tv:
    name: Tv
    entities:
    - media_player.tv
    - media_player.yamaha_receiver
    - switch.tv
    - group.tv_timer

  tv_timer:
    name: Tv Timer
    entities:
    - sensor.tv_timer
    - input_slider.tv_timer
    - script.tv_shutdown_timer
  yamaha_input:
    - sensor.spotify_input
    - sensor.yamaha_input
    - script.yamaha_source_blue
    - script.yamaha_source_tv
    - script.yamaha_source_alexa
    - script.play_spotify_echo
    - script.play_spotify_alexa

homeassistant:
  customize:
    group.tv_timer:
      custom_ui_state_card: state-card-custom-ui
      extra_badge:
        entity_id: sensor.tv_timer
      icon: mdi:timer
    switch.tv:
      icon: mdi:monitor
