### automation ###
automation:
  - alias: Cube event flip90
    initial_state: 'on'
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000103a328
        action_type: flip90
    action:
      # - service: light.turn_on
        # entity_id: light.gateway_light_34ce008c0676
        # data:
          # color_name: "springgreen"
      - service: switch.toggle
        entity_id: switch.living_switch_1

  - alias: Cube event flip180
    initial_state: 'on'
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000103a328
        action_type: flip180
    action:
      # - service: light.turn_on
        # entity_id: light.gateway_light_34ce008c0676
        # data:
          # color_name: "darkviolet"
      - service: switch.turn_off
        entity_id: switch.living_switch_1
      - service: switch.turn_off
        entity_id: switch.living_switch_2

  - alias: Cube event move
    initial_state: 'on'
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000103a328
        action_type: move
    action:
      - service: media_player.media_play
        entity_id: media_player.spotify

  - alias: Cube event tap_twice
    initial_state: 'on'
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000103a328
        action_type: tap_twice
    action:
      - service: switch.toggle
        entity_id: switch.living_switch_2

  - alias: Cube event shake_air
    initial_state: 'on'
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000103a328
        action_type: shake_air
    action:
      # - service: light.turn_on
        # entity_id: light.gateway_light_34ce008c0676
        # data:
          # color_name: "blue"
      - service: input_select.select_option
        data_template:
          entity_id: input_select.mode
          option: >-
            {% if is_state('input_select.mode', 'Home') %}
              Zzz
            {% else %}
              Home
            {% endif %}
      
          
  - alias: Cube event swing
    initial_state: 'off'
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000103a328
        action_type: swing
    action:
      - service: light.turn_on
        entity_id: light.gateway_light_34ce008c0676
        data:
          color_name: "red"
  - alias: Cube event alert
    initial_state: 'off'
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000103a328
        action_type: alert
    action:
      # - service: light.turn_on
        # entity_id: light.gateway_light_34ce008c0676
        # data:
          # color_name: "green"
      - service: input_select.select_option
        data:
          entity_id: input_select.mode
          option: Home
  - alias: Cube event free_fall
    initial_state: 'on'
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000103a328
        action_type: free_fall
    action:
      - service: script.play_spotify_alexa

  - alias: Cube event rotate
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000103a328
        action_type: rotate
    action:
#      - service: input_number.select_value
#        data_template:
#          entity_id: input_number.cube_rotate
#          value: '{{ trigger.event.data.action_value | float }}'
#      - service: input_slider.select_value
#        data_template:
#          entity_id: input_slider.room_light
#          value: >-
#            {%if (trigger.event.data.action_value | int > 25) and (states.input_slider.room_light.state | int < 2) %}
#            2
#            {% elif (trigger.event.data.action_value | int) < -25 and (states.input_slider.room_light.state | int > 0) %}
#            0
#            {% elif (trigger.event.data.action_value | int > 0) and (states.input_slider.room_light.state | int < 2) %}
#            {{ (states.input_slider.room_light.state | int) + 1 }}
#            {% elif (trigger.event.data.action_value | int) < 0 and (states.input_slider.room_light.state | int > 0) %}
#            {{ (states.input_slider.room_light.state | int) - 1 }}
#            {% else %}
#            {{ states.input_slider.room_light.state | int }}
#            {% endif %}

      - service: media_player.volume_set
        data_template:
          entity_id: media_player.yamaha_receiver
          volume_level: >
                      {% set state = states.media_player.yamaha_receiver.attributes.volume_level + (trigger.event.data.action_value|float)/90 -%}
                      {%-  if state > 1 -%}
                         {%- set state  = 1 -%}
                      {%-  elif state < 0 -%}
                         {%- set state  = 0 -%}
                      {%- endif %}
                      {{ state }}
            
  - alias: Cube event rotate light tracker 0
    trigger:
      platform: state
      entity_id: input_number.room_light
      to: '0.0'
    action:
      - service: switch.turn_off
        entity_id: switch.living_switch_1
      - service: switch.turn_off
        entity_id: switch.living_switch_2
        
  - alias: Cube event rotate light tracker 1
    trigger:
      platform: state
      entity_id: input_number.room_light
      to: '1.0'
    action:
      - service: switch.turn_on
        entity_id: switch.living_switch_1
      - service: switch.turn_off
        entity_id: switch.living_switch_2
        
  - alias: Cube event rotate light tracker 2
    trigger:
      platform: state
      entity_id: input_number.room_light
      to: '2.0'
    action:
      - service: switch.turn_on
        entity_id: switch.living_switch_1
      - service: switch.turn_on
        entity_id: switch.living_switch_2

input_number:
  cube_rotate:
    name: cube_rotate
    min: -200
    max: 200
    step: 10
    initial: 0
    mode: box
  room_light:
    name: room_light
    min: 0
    max: 2
    step: 1
    initial: 0
    mode: box

group:
  mi_cube_automation:
    entities:
      - automation.cube_event_alert
      - automation.cube_event_flip180
      - automation.cube_event_flip90
      - automation.cube_event_free_fall
      - automation.cube_event_move
      - automation.cube_event_rotate
      - automation.cube_event_rotate_light_tracker_0
      - automation.cube_event_rotate_light_tracker_1
      - automation.cube_event_rotate_light_tracker_2
      - automation.cube_event_shake_air
      - automation.cube_event_swing
      - automation.cube_event_tap_twice

homeassistant:
  customize:
    binary_sensor.cube_158d000103a328:
      custom_ui_state_card: state-card-custom-ui
      extra_data_template: ${ entities['input_number.cube_rotate'].state}
      friendly_name: Cube
      icon: mdi:cube-outline
    group.mi_cube_automation:
      custom_ui_state_card: state-card-custom-ui
      extra_data_template: ${ entities['input_number.cube_rotate'].state}
      friendly_name: Cube Settings
      icon: mdi:cube-outline


